FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d

COPY ./views /usr/share/nginx/html
COPY ./style /usr/share/nginx/html/style

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]